name: Deploy Logic App to Azure

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  AZURE_RESOURCE_GROUP: az-d-rg-b2bIntegration
  LOGIC_APP_NAME: az-d-lap-ApiTranslator-eus-03
  LOCATION: eastus

jobs:
  deploy:
    name: Deploy to Dev Environment
    runs-on: ubuntu-latest
    environment: dev
    
    permissions:
      id-token: write
      contents: read
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Azure Login using OIDC
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
    - name: Set up Node.js for Azure Functions Core Tools
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install Azure Functions Core Tools
      run: |
        npm install -g azure-functions-core-tools@4 --unsafe-perm true
        
    - name: Verify Azure CLI installation
      run: |
        az --version
        az account show
        
    - name: Deploy Infrastructure (if needed)
      run: |
        # Check if infrastructure exists
        if ! az logicapp show --name ${{ env.LOGIC_APP_NAME }} --resource-group ${{ env.AZURE_RESOURCE_GROUP }} >/dev/null 2>&1; then
          echo "Infrastructure not found, would need to deploy Bicep templates"
          echo "Skipping infrastructure deployment as it already exists"
        else
          echo "Logic App infrastructure already exists"
        fi
        
    - name: Configure Logic App Settings
      run: |
        # Ensure required app settings are configured for Logic Apps Standard
        az logicapp config appsettings set \
          --name ${{ env.LOGIC_APP_NAME }} \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --settings \
            "APP_KIND=workflowapp" \
            "FUNCTIONS_WORKER_RUNTIME=dotnet" \
            "FUNCTIONS_INPROC_NET8_ENABLED=1" \
            "WEBSITE_NODE_DEFAULT_VERSION=~18"
            
    - name: Deploy Logic App Workflow
      run: |
        cd ApiTranslator/ApiTranslator
        
        # Create deployment package
        zip -r ../../logicapp-deployment.zip . -x "*.git*" "*.vs*" "local.settings.json"
        cd ../..

        # Deploy using Logic App-specific Azure CLI commands
        az logicapp deployment source config-zip \
          --name ${{ env.LOGIC_APP_NAME }} \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --src logicapp-deployment.zip    - name: Wait for deployment sync
      run: |
        echo "Waiting for Logic App to sync workflows..."
        sleep 60
        
    - name: Verify deployment
      run: |
        # Check Logic App status using logicapp commands
        az logicapp show \
          --name ${{ env.LOGIC_APP_NAME }} \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --query "{name:name, state:state, defaultHostName:defaultHostName}" \
          --output table
          
        # List workflows using REST API since az logicapp workflow commands don't exist
        echo "Checking for deployed workflows..."
        az rest \
          --method GET \
          --uri "https://management.azure.com/subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${{ env.AZURE_RESOURCE_GROUP }}/providers/Microsoft.Web/sites/${{ env.LOGIC_APP_NAME }}/hostruntime/admin/workflows?api-version=2022-03-01" \
          --query "value[].{name:name, state:properties.state}" \
          --output table || echo "No workflows found yet"
          
    - name: Test deployment health
      run: |
        # Simple health check
        curl -f "https://${{ env.LOGIC_APP_NAME }}.azurewebsites.net" || echo "Health check endpoint not responding"
